# Generated by Django 4.2.4 on 2023-08-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
