# Generated by Django 4.1.7 on 2023-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='use',
            field=models.TextField(default=''),
        ),
    ]
