# Generated by Django 4.2.4 on 2023-10-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_medicine_details_medicine_price_medicine_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
