# Generated by Django 4.2.4 on 2023-10-05 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_category'),
        ('staff', '0005_remove_medicine_brand_id_remove_medicine_cat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField(default='0')),
                ('details', models.TextField(default='')),
                ('use', models.TextField(default='')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.category')),
            ],
        ),
    ]
