# Generated by Django 4.2.4 on 2023-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock',
            field=models.IntegerField(default='1'),
        ),
    ]
