# Generated by Django 4.2.4 on 2023-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
