# Generated by Django 4.2.4 on 2023-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_delete_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('staff_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(default='enter address')),
                ('role', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='staffImage')),
                ('biodata', models.FileField(upload_to='resumes')),
                ('join_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
